# Menggunakan image dasar dari Python
FROM python:3.9-slim

# Menyiapkan direktori kerja di dalam container
WORKDIR /app

# Menyalin requirements dan menginstal dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Menyalin file script untuk inferensi
COPY model_inference.py .

# Menjalankan service pada port 5002
EXPOSE 5002

# Menjalankan aplikasi
CMD ["python", "model_inference.py"]
